version: "3.9"

services:
  web:
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - DB_URI=redis://db:6379
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "redis:${IMAGE_VERSION_REDIS:-7.0.9-bullseye}"
    ports:
      - "6379:6379"